### ISSUE TITLE
plotEXP

### ISSUE THREAD

**Issue by lucas2chen** [isglobal-brge/rexposome#5]
When using the method `plotEXP` to draw a heat map with the correlation of each exposure to the principal components, is it possible to specify which type of correlation we are using, for example, Pearson or Spearman? I couldn't find this specification or function in the CODE.

**Comment by ESCRI11** [comment]
The correlation plotted by this function is actually calculated by FactoMineR when calculating the PCA. More information here: http://factominer.free.fr/factomethods/principal-components-analysis.html
